def canonicalize(json_bytes: bytes) -> bytes: ...
def hash_sha256(data: bytes) -> str: ...
def compute_merkle_root(digests: list[str]) -> str: ...
def sign_bundle_root(root: str, key_pem: str, kid: str) -> str: ...
def verify_bundle_root(jws: str, expected_root: str, pub_key_pem: str) -> bool: ...
def build_bundle_json(
    capture_json: str,
    artefacts_json: str,
    key_pem: str,
    kid: str,
    bundle_id: str,
    created_at: str,
) -> str: ...
def verify_bundle(bundle_json: str, artefacts_json: str, pub_key_pem: str) -> str: ...
def evaluate_completeness_json(bundle_json: str, profile: str) -> str: ...
